apiVersion: apps/v1
kind: Deployment
metadata: 
  name: db-demo-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: db-demo-app
  template:
    metadata:
      labels:
        app: db-demo-app
    spec:
      containers:
      - name: db-demo-app
        image: bhargav200004/webapp-demo:22 
        imagePullPolicy: Always
        env:
          - name: MONGO_HOST
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: MONGO_HOST  
          - name: MONGO_PORT
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: MONGO_PORT 

---
apiVersion: v1
kind: Service
metadata:
  name: service-db-demo-app
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 3000
  selector:
    app: db-demo-app
  type: LoadBalancer